"""Description of changes

Revision ID: 21d80cafbd20
Revises: 
Create Date: 2024-09-11 17:40:09.293593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d80cafbd20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasted_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipeItem', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('forecasted_quantity', sa.Float(), nullable=False),
    sa.Column('mean_se', sa.Float(), nullable=False),
    sa.Column('ci_lower', sa.Float(), nullable=False),
    sa.Column('ci_upper', sa.Float(), nullable=False),
    sa.Column('actual_quantity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecasted_values', schema=None) as batch_op:
        batch_op.create_index('idx_recipe_date', ['recipeItem', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecasted_values', schema=None) as batch_op:
        batch_op.drop_index('idx_recipe_date')

    op.drop_table('forecasted_values')
    # ### end Alembic commands ###
