"""Added dateToday column to forecasted_values

Revision ID: 49a8a87df85e
Revises: 21d80cafbd20
Create Date: 2024-11-20 18:06:02.102968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a8a87df85e'
down_revision = '21d80cafbd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecasted_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateToday', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecasted_values', schema=None) as batch_op:
        batch_op.drop_column('dateToday')

    # ### end Alembic commands ###
